
[cursor.style]
shape = "Block"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = true
opacity = 0.7

[window.padding]
x = 0
y = 0

[general]
# [colors.bright]
# black = "#393939"
# blue = "#33b1ff"
# cyan = "#3ddbd9"
# green = "#42be65"
# magenta = "#ff7eb6"
# red = "#ee5396"
# white = "#ffffff"
# yellow = "#ffe97b"
#
# [colors.normal]
# black = "#262626"
# blue = "#33b1ff"
# cyan = "#3ddbd9"
# green = "#42be65"
# magenta = "#ff7eb6"
# red = "#ee5396"
# white = "#dde1e6"
# yellow = "#ffe97b"
#
# [colors.primary]
# background = "#161616"
# foreground = "#ffffff"
#
# [colors.search.matches]
# background = "#ee5396"
# foreground = "CellBackground"

import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]
