# Startup apps and services config file



# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox


exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = uwsm app hyprpaper
#exec-once = uwsm app waybar
#exec-once = uwsm app swaync

# clippy
# exec-once = uwsm app wl-paste --type text --watch cliphist -max-items 36 store #Stores only text data
# exec-once = uwsm app wl-paste --type image --watch cliphist -max-items 36 store #Stores only image data

#exec-once = hyprland-per-window-layout

exec-once = uwsm app udiskie

#exec-once = uwsm app /usr/libexec/hyprpolkitagent 
#exec-once = uwsm app hypridle
#exec-once = hyprsunset

exec-once = uwsm app kdeconnect-indicator

# audit (apparmor) logger
# exec-once = aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log

#exec-once = uwsm app gnome-keyring-daemon --start --components=pkcs11,secrets,ssh

# something keeps changing my cursor. This is my ultimatum.
exec-once = gsettings set org.gnome.desktop.interface cursor-theme Adwaita
